todo-app/todo-app-mvc/Models/ErrorViewModel.cs
using System;

namespace todo_app_mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

todo-app/todo-app-mvc/Controllers/ToDoListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using todo_app_lib.Data;
using todo_app_lib.Models;
using todo_app_lib;

namespace todo_app_mvc.Controllers
{
    public class ToDoListsController : Controller
    {
        private readonly ToDoAppContext _context;

        public ToDoListsController(ToDoAppContext context)
        {
            _context = context;
        }

        // GET: ToDoLists
        public async Task<IActionResult> Index()
        {
            return View(await _context.ToDoLists.Include(list => list.ToDoEntries).ToListAsync());
        }

        // GET: ToDoLists/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoList = DbInteraction.ObtainList((int)id, _context);
            if (toDoList == null)
            {
                return NotFound();
            }

            return View(toDoList);
        }

        public IActionResult CopyList(int id)
        {
            try
            {
                var toDoList = DbInteraction.ObtainList(id, _context);
                DbInteraction.CreateToDoList(toDoList.Name, toDoList.ToDoEntries, _context);
            }
            catch (Exception e)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: ToDoLists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ToDoLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] ToDoList toDoList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(toDoList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(toDoList);
        }

        public IActionResult AddEntry(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddEntry(int id, [Bind("Title,Description,DueDate,Status")] ToDoEntry entry)
        {
            if (ModelState.IsValid)
            {
                DbInteraction.AssignEntry(id, entry, _context);
                return RedirectToAction(nameof(Edit), new {id = id});
            }
            return View(_context.ToDoLists
                .FirstOrDefaultAsync(m => m.Id == id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteEntry(int id, int listId)
        {
            try
            {
                DbInteraction.RemoveEntry(id, _context);
            }
            catch (Exception e)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Edit), new { id = listId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult StartTask(int id, int listId)
        {
            try
            {
                DbInteraction.StartTask(id, _context);
            }
            catch (Exception e)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Details), new {id = listId});
        }

        public IActionResult CompleteTask(int id, int listId)
        {
            try
            {
                DbInteraction.CompleteTask(id, _context);
            }
            catch (Exception e)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Details), new { id = listId });
        }

        public IActionResult EditEntry(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ToDoEntry entry;
            try
            {
                entry = DbInteraction.ObtainEntry(_context, (int)id);
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(entry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditEntry(int id, [Bind("Id,Title,Description,DueDate,Status")] ToDoEntry entry)
        {
            if (id != entry.Id)
            {
                throw new ArgumentException("Form error, id changed");
            }

            int listId;
            if (ModelState.IsValid)
            {
                try
                {
                    listId = DbInteraction.ModifyEntry(id, entry, _context);
                }
                catch (Exception)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Edit), new { id = listId});
            }
            return View(entry);
        }

        // GET: ToDoLists/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ToDoList toDoList;
            try
            {
                toDoList = DbInteraction.ObtainList((int)id, _context);
            }
            catch (Exception)
            {
                return NotFound();
            }

            return View(toDoList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] ToDoList toDoList)
        {
            if (id != toDoList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(toDoList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoListExists(toDoList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(toDoList);
        }

        // GET: ToDoLists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoList = await _context.ToDoLists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoList == null)
            {
                return NotFound();
            }

            return View(toDoList);
        }

        // POST: ToDoLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                DbInteraction.RemoveToDoList(id, _context);
            }
            catch(Exception e)
            {
                return NotFound();
            }     
            
            return RedirectToAction(nameof(Index));
        }

        private bool ToDoListExists(int id)
        {
            return _context.ToDoLists.Any(e => e.Id == id);
        }
    }
}

todo-app/todo-app-mvc/Views/Shared/ToDoEntry.cshtml
@model todo_app_lib.Models.ToDoEntry

@{
    string statusColor;
    string completedClass = Model.Status == "Completed" ? "completed" : "";
    switch (Model.Status)
    {
        case "Not Started":
            statusColor = "text-danger";
            break;
        case "In Progress":
            statusColor = "text-warning";
            break;
        case "Completed":
            statusColor = "text-success";
            break;
        default:
            statusColor = "text-muted";
            break;
    }
}
    <div class="card m-2 @completedClass" style="width: 50rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
            <h6 class="card-subtitle mb-2 text-muted">Due Date: @Model.DueDate.ToString("MMMM dd", CultureInfo.InvariantCulture)</h6>
            <h6 class="card-subtitle mb-2 @statusColor">Task Status: @Model.Status</h6>
        </div>
    </div>

todo-app/todo-app-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="ToDoLists" asp-action="Index">ToDo App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

todo-app/todo-app-mvc/Views/ToDoLists/AddEntry.cshtml
@model todo_app_lib.Models.ToDoEntry

@{
    ViewData["Title"] = "New entry";
}

<h1>Add Entry</h1>

<h4>Entry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddEntry">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-app/todo-app-mvc/Views/ToDoLists/Create.cshtml
@model todo_app_lib.Models.ToDoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ToDoList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-app/todo-app-mvc/Views/ToDoLists/Delete.cshtml
@model todo_app_lib.Models.ToDoList

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDoList</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

todo-app/todo-app-mvc/Views/ToDoLists/Details.cshtml
@model todo_app_lib.Models.ToDoList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>


    <h4>@Model.Name</h4>
<button class="btn btn-link" id="hide-btn" onclick="changeViewStyle()">Hide Completed Items</button>
    <div class="d-flex justify-content-start flex-wrap align-items-center" style="width: 100%;">

        @foreach (var entry in Model.ToDoEntries)
        {
            <div class="d-flex justify-content-around" align-items-center>
                @{await Html.RenderPartialAsync("ToDoEntry", entry);
                }

            </div>
            if (entry.Status != "Completed")
            {
                if (entry.Status == "Not Started")
                {
                    <form asp-action="StartTask" asp-route-id="@entry.Id" asp-route-listId="@Model.Id">
                        <input type="submit" value="Start" class="btn btn-outline-primary" />
                    </form>
                }

                else if (entry.Status == "In Progress")
                {
                    <form asp-action="CompleteTask" asp-route-id="@entry.Id" asp-route-listId="@Model.Id">
                        <input type="submit" value="Finish" class="btn btn-success" />
                    </form>
                }
            }
        }


    </div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{ 
    <script >
        function changeViewStyle() {
            const cards = document.getElementsByClassName("card");
            const button = document.getElementById("hide-btn");

            if (button.textContent == "Hide Completed Items") {
                button.textContent = "Show Completed Items";
            }
            else button.textContent = "Hide Completed Items";

            for (let i = 0; i < cards.length; ++i) {
                if (cards[i].classList.contains("completed")) {
                    if (cards[i].style.display != "none") {
                        cards[i].style.display = "none";
                    }
                    else {
                        cards[i].style.display = "flex";
                    }
                }
            }
        }
    </script>
}

todo-app/todo-app-mvc/Views/ToDoLists/Edit.cshtml
@model todo_app_lib.Models.ToDoList

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoList</h4>
<hr />
<div>
    <div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <a asp-action="AddEntry" asp-route-id="@Model.Id">Add New Task</a>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div class="d-flex justify-content-around flex-wrap align-items-center" style="width: 100%;">
            @foreach (var entry in Model.ToDoEntries)
            {
                string statusColor;
                switch (entry.Status)
                {
                    case "Not Started":
                        statusColor = "text-danger";
                        break;
                    case "In Progress":
                        statusColor = "text-warning";
                        break;
                    case "Completed":
                        statusColor = "text-success";
                        break;
                    default:
                        statusColor = "text-muted";
                        break;
                }

                <div class="card m-2" style="width: 25rem;">
                    <div class="card-body">
                        <h5 class="card-title">@entry.Title</h5>
                        <p class="card-text">@entry.Description</p>
                        <h6 class="card-subtitle mb-2 text-muted">Due Date: @entry.DueDate.ToString("MMMM dd")</h6>
                        <h6 class="card-subtitle mb-2 @statusColor">Task Status: @entry.Status</h6>
                        <div class="d-flex justify-content-between" style="width: 45%">
                            <a asp-action="EditEntry" asp-route-id="@entry.Id" class="btn btn-primary">Edit</a>
                            <form asp-action="DeleteEntry" asp-route-id="@entry.Id" , asp-route-listId="@Model.Id">
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-app/todo-app-mvc/Views/ToDoLists/EditEntry.cshtml
@model todo_app_lib.Models.ToDoEntry

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoEntry</h4>
<hr />
<div>
    <div>
        <form asp-action="EditEntry">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label><br />
                <input type="radio" asp-for="Status" value="Not Started" />Not Started<br />
                <input type="radio" asp-for="Status" value="In Progress" />In Progress<br />
                <input type="radio" asp-for="Status" value="Completed" />Completed<br />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.ToDoListId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

todo-app/todo-app-mvc/Views/ToDoLists/Index.cshtml
@model IEnumerable<todo_app_lib.Models.ToDoList>

@{
    ViewData["Title"] = "Index";
}

<h1>ToDo Lists</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Number of tasks
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ToDoEntries.Count)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Expand</a> |
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                    <form asp-action="CopyList" asp-route-id="@item.Id">
                        <input type="submit" value="Make a copy" class="btn btn-link" />
                    </form>
                </td>
            </tr>
    }
    </tbody>
</table>
<div>
    <h2>Today's Tasks</h2>
    @{ bool tasksDueToday = false;}
    @foreach (var item in Model)
    {
        if (item.ToDoEntries.FirstOrDefault(item => item.DueDate.Date == DateTime.Now.Date) != null)
        {
            <h3>@item.Name</h3>
            foreach (var entry in item.ToDoEntries)
            {
                if (entry.DueDate.Date == DateTime.Now.Date)
                {
                <div class="d-flex align-items-md-center justify-content-center">
                    @{tasksDueToday = true;
                        }
                        @{await Html.RenderPartialAsync("ToDoEntry", entry);
                        }

                    @if (entry.Status != "Completed")
                    {
                        if (entry.Status == "Not Started")
                        {
                            <form asp-action="StartTask" asp-route-id="@entry.Id" asp-route-listId="@item.Id">
                                <input type="submit" value="Start" class="btn btn-outline-primary" />
                            </form>
                        }

                        else if (entry.Status == "In Progress")
                        {
                            <form asp-action="CompleteTask" asp-route-id="@entry.Id" asp-route-listId="@item.Id">
                                <input type="submit" value="Finish" class="btn btn-success" />
                            </form>
                        }
                    }
                </div>
                }
            }
        }
    }

    @if (!tasksDueToday)
    {
        <h3>No tasks due today</h3>
    }
</div>